## Looping through the Fantasy Premier League API “Element-Summary” Endpoint to Download Player History with Python and Pandas

[Post on Medium](https://towardsdatascience.com/looping-through-the-fantasy-premier-league-api-element-summary-endpoint-to-download-player-df4ab5151fcb)

### Imports

In [2]:
import pandas as pd
import requests

### Settings

In [3]:
pd.options.display.max_columns = None

### Api Requests

In [4]:
url = 'https://fantasy.premierleague.com/api/bootstrap-static/'

In [5]:
r = requests.get(url)

### Transform response to JSON

In [6]:
json = r.json()

### Create DataFrames using JSON

In [7]:
json.keys()

dict_keys(['events', 'game_settings', 'phases', 'teams', 'total_players', 'elements', 'element_stats', 'element_types'])

In [8]:
elements_df = pd.DataFrame(json['elements'])

In [9]:
elements_df.head()

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,id,in_dreamteam,news,news_added,now_cost,photo,points_per_game,second_name,selected_by_percent,special,squad_number,status,team,team_code,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text
0,0.0,0.0,37605,0,0,-3,3,0,3,0.0,0.0,0,Mesut,0.0,1,False,Not included in Arsenal's 25-man Premier Leagu...,2020-10-20T22:30:18.118477Z,67,37605.jpg,0.0,Özil,0.5,False,None,u,1,3,0,3441,3,53560,129,0.0,0.0,Özil,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,639,256,639,256,639,256,639,256,NaN,,NaN,,NaN,
1,0.0,0.0,39476,0,0,-2,2,0,2,0.0,0.0,0,Sokratis,0.0,2,False,Left the club by mutual consent on 20/1,2020-10-21T10:30:18.546407Z,48,39476.jpg,0.0,Papastathopoulos,0.1,False,None,u,1,3,0,10266,1,18938,13,0.0,0.0,Sokratis,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,599,219,589,219,582,215,602,219,NaN,,NaN,,NaN,
2,100.0,100.0,41270,0,0,-1,1,0,2,2.7,2.7,6,David,2.2,3,False,,2020-12-26T18:00:15.638627Z,54,41270.jpg,2.0,Luiz Moreira Marinho,0.8,False,None,a,1,3,20,42617,738,92416,467,0.4,3.7,David Luiz,659,0,0,2,9,0,0,0,1,0,0,0,108,115.4,28.8,56.0,20.0,259,99,312,100,250,76,297,97,NaN,,4.0,,NaN,
3,100.0,100.0,54694,0,0,-7,7,1,3,5.3,5.3,15,Pierre-Emerick,4.8,4,False,,2020-12-19T20:30:20.434896Z,113,54694.jpg,4.2,Aubameyang,7.0,False,None,a,1,3,71,534993,11824,3197629,4655,0.4,6.3,Aubameyang,1514,5,1,7,16,1,0,0,2,0,0,6,202,272.2,226.3,519.0,101.8,113,39,67,47,20,12,32,22,NaN,,NaN,,1.0,
4,100.0,100.0,58822,0,0,-4,4,0,2,2.9,2.9,12,Cédric,2.4,5,False,,2020-09-23T09:00:14.881983Z,46,58822.jpg,6.5,Soares,0.2,False,None,a,1,3,13,5366,1031,35500,223,0.5,2.8,Cédric,95,0,1,1,0,0,0,0,0,0,0,3,42,29.2,32.3,2.0,6.4,381,151,302,93,400,151,386,145,NaN,,NaN,,NaN,

### Build and Test a For Loop

In [10]:
for x in elements_df.index[:10] :
    element_id = elements_df.id[x]
    element_name = elements_df.first_name[x]
    print("Id is " + str(element_id))
    print("Name is " + str(element_name))

Id is 1
Name is Mesut
Id is 2
Name is Sokratis
Id is 3
Name is David
Id is 4
Name is Pierre-Emerick
Id is 5
Name is Cédric
Id is 6
Name is Alexandre
Id is 7
Name is Shkodran
Id is 8
Name is Bernd
Id is 9
Name is Granit
Id is 10
Name is Pablo

### Iterate Through All Elements and Build Master DataFrames with f-string Formatting

In [11]:
player_url = 'https://fantasy.premierleague.com/api/element-summary/1/'

In [12]:
your_name = "David"
print(f"Hi, my name is {your_name}")

Hi, my name is David

In [13]:
player_request = requests.get(player_url)
player_json = player_request.json()
player_json.keys()

dict_keys(['fixtures', 'history', 'history_past'])

In [14]:
player_fixtures_df = pd.DataFrame(player_json['fixtures'])
player_history_df = pd.DataFrame(player_json['history'])
player_history_past_df = pd.DataFrame(player_json['history_past'])

In [15]:
player_fixtures_df.head()

,id,code,team_h,team_h_score,team_a,team_a_score,event,finished,minutes,provisional_start_time,kickoff_time,event_name,is_home,difficulty
0,197,2128484,16,None,1,None,20,False,0,False,2021-01-26T20:15:00Z,Gameweek 20,False,3
1,199,2128486,1,None,13,None,21,False,0,False,2021-01-30T17:30:00Z,Gameweek 21,True,4
2,215,2128502,20,None,1,None,22,False,0,False,2021-02-02T18:00:00Z,Gameweek 22,False,3
3,219,2128506,2,None,1,None,23,False,0,False,2021-02-06T12:30:00Z,Gameweek 23,False,3
4,229,2128516,1,None,10,None,24,False,0,False,2021-02-14T16:30:00Z,Gameweek 24,True,2

In [16]:
player_history_df.head()

,element,fixture,opponent_team,total_points,was_home,kickoff_time,team_h_score,team_a_score,round,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,value,transfers_balance,selected,transfers_in,transfers_out
0,1,2,8,0,False,2020-09-12T11:30:00Z,0,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,70,0,76656,0,0
1,1,9,19,0,True,2020-09-19T19:00:00Z,2,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,69,-16828,68335,995,17823
2,1,23,11,0,False,2020-09-28T19:00:00Z,3,1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,69,-11451,59793,675,12126
3,1,29,15,0,True,2020-10-04T13:00:00Z,2,1,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,68,-5324,56403,647,5971
4,1,44,12,0,False,2020-10-17T16:30:00Z,1,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,68,-4224,53689,616,4840

In [17]:
player_history_past_df.head()

,season_name,element_code,start_cost,end_cost,total_points,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index
0,2013/14,37605,100,96,137,2141,5,10,13,23,0,0,0,0,0,0,18,162,0.0,0.0,0.0,0.0
1,2014/15,37605,90,90,103,1857,4,6,9,16,0,0,0,0,0,0,13,511,0.0,0.0,0.0,0.0
2,2015/16,37605,85,92,200,3036,6,19,17,31,0,0,0,4,0,0,30,861,0.0,0.0,0.0,0.0
3,2016/17,37605,95,95,167,2841,8,11,12,30,0,0,0,2,0,0,19,729,834.4,1649.3,734.0,322.0
4,2017/18,37605,95,93,112,2161,4,9,8,36,0,0,0,4,0,0,11,506,640.6,1287.5,555.0,248.6

In [18]:
for x in elements_df.index[:5] :
    print(x)
    element_id = elements_df.id[x]
    player_url = f'https://fantasy.premierleague.com/api/element-summary/{element_id}/'
    player_resp = requests.get(player_url)
    player_json = player_resp.json()
    player_json_history_df = pd.DataFrame(player_json['history'])
    player_json_history_past_df = pd.DataFrame(player_json['history_past'])
    if x == 0 :
        all_history_df = player_json_history_df
        all_history_past_df = player_json_history_past_df
    else : 
        all_history_df = all_history_df.append(player_json_history_df)
        all_history_past_df = all_history_past_df.append(player_json_history_past_df)

0
1
2
3
4

In [19]:
all_history_df.head(10)

,element,fixture,opponent_team,total_points,was_home,kickoff_time,team_h_score,team_a_score,round,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,value,transfers_balance,selected,transfers_in,transfers_out
0,1,2,8,0,False,2020-09-12T11:30:00Z,0,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,70,0,76656,0,0
1,1,9,19,0,True,2020-09-19T19:00:00Z,2,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,69,-16828,68335,995,17823
2,1,23,11,0,False,2020-09-28T19:00:00Z,3,1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,69,-11451,59793,675,12126
3,1,29,15,0,True,2020-10-04T13:00:00Z,2,1,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,68,-5324,56403,647,5971
4,1,44,12,0,False,2020-10-17T16:30:00Z,1,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,68,-4224,53689,616,4840
5,1,49,9,0,True,2020-10-25T19:15:00Z,0,1,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,68,-3184,51023,276,3460
6,1,64,13,0,False,2020-11-01T16:30:00Z,0,1,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,68,-3147,48026,57,3204
7,1,69,2,0,True,2020-11-08T19:15:00Z,0,3,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,68,-1691,46467,38,1729
8,1,82,10,0,False,2020-11-22T16:30:00Z,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,68,-1364,45182,14,1378
9,1,89,20,0,True,2020-11-29T19:15:00Z,1,2,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,68,-525,44753,12,537

In [20]:
all_history_past_df.head(10)

,season_name,element_code,start_cost,end_cost,total_points,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index
0,2013/14,37605,100,96,137,2141,5,10,13,23,0,0,0,0,0,0,18,162,0.0,0.0,0.0,0.0
1,2014/15,37605,90,90,103,1857,4,6,9,16,0,0,0,0,0,0,13,511,0.0,0.0,0.0,0.0
2,2015/16,37605,85,92,200,3036,6,19,17,31,0,0,0,4,0,0,30,861,0.0,0.0,0.0,0.0
3,2016/17,37605,95,95,167,2841,8,11,12,30,0,0,0,2,0,0,19,729,834.4,1649.3,734.0,322.0
4,2017/18,37605,95,93,112,2161,4,9,8,36,0,0,0,4,0,0,11,506,640.6,1287.5,555.0,248.6
5,2018/19,37605,85,79,89,1732,5,3,5,24,0,0,0,2,0,0,9,363,429.6,714.2,254.0,140.0
6,2019/20,37605,75,69,53,1439,1,3,5,20,0,0,0,1,0,0,1,256,223.6,582.9,190.0,99.8
0,2018/19,39476,55,51,64,2198,1,2,5,33,0,0,0,12,0,0,4,402,513.8,67.9,120.0,70.4
1,2019/20,39476,50,48,57,1696,2,0,4,25,0,0,0,6,0,0,5,305,436.2,36.8,110.0,58.5
0,2010/11,41270,60,65,56,953,2,0,4,8,0,0,0,3,0,0,10,0,0.0,0.0,0.0,0.0

### Save to CSV and Pickle

In [22]:
all_history_df.to_csv('~/Projects/fantasyfootball/all_history_df_20_21.csv')

In [23]:
all_history_past_df.to_csv('~/Projects/fantasyfootball/all_history_past_df_20_21.csv')